# Generated by Django 5.0.6 on 2024-05-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booker_name', models.CharField(max_length=100)),
                ('floor_number', models.IntegerField()),
                ('unit_number', models.IntegerField()),
                ('facility', models.CharField(choices=[('common-room', 'Common Room'), ('hall-room', 'Hall Room'), ('swimming-pool', 'Swimming Pool'), ('bbq-area', 'BBQ Area'), ('rooftop-terrace', 'Rooftop Terrace'), ('sports-facilities', 'Sports Facilities')], max_length=50)),
                ('booking_date', models.DateField()),
                ('booking_time', models.CharField(choices=[('9:00 am To 10:00 am', '9:00 am To 10:00 am'), ('10:00 am To 11:00 am', '10:00 am To 11:00 am'), ('11:00 am To 12:00 pm', '11:00 am To 12:00 pm'), ('12:00 pm To 1:00 pm', '12:00 pm To 1:00 pm'), ('1:00 pm To 2:00 pm', '1:00 pm To 2:00 pm'), ('2:00 pm To 3:00 pm', '2:00 pm To 3:00 pm'), ('3:00 pm To 4:00 pm', '3:00 pm To 4:00 pm'), ('4:00 pm To 5:00 pm', '4:00 pm To 5:00 pm'), ('5:00 pm To 6:00 pm', '5:00 pm To 6:00 pm'), ('6:00 pm To 7:00 pm', '6:00 pm To 7:00 pm'), ('7:00 pm To 8:00 pm', '7:00 pm To 8:00 pm'), ('8:00 pm To 9:00 pm', '8:00 pm To 9:00 pm')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approved'), ('rejected', 'Rejected')], default='Pending', max_length=20)),
                ('attendees', models.IntegerField()),
                ('additional_notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenenceRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('issue_type', models.CharField(choices=[('Appliance', 'Appliance Repair'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('House-Exterior', 'House Exterior'), ('Outdoors', 'Outdoors'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=64)),
                ('request_datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=20)),
            ],
        ),
    ]
