# Generated by Django 5.0.6 on 2024-05-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenenceRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('issue_type', models.CharField(choices=[('Appliance', 'Appliance Repair'), ('Plumbing', 'Plumbing'), ('Electrical', 'Electrical'), ('House-Exterior', 'House Exterior'), ('Outdoors', 'Outdoors'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=64)),
                ('request_datetime', models.DateTimeField()),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=20)),
            ],
        ),
    ]
