# Generated by Django 5.0.6 on 2024-06-27 16:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addform1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('home_address', models.TextField()),
                ('passport_or_nric', models.FileField(blank=True, null=True, upload_to='media/')),
                ('driving_license', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Addform2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness_center', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('parking_facilities', models.BooleanField(default=False)),
                ('children_play_area', models.BooleanField(default=False)),
                ('clubhouse', models.BooleanField(default=False)),
                ('playground', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Addform3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contract_term', models.PositiveIntegerField(choices=[(6, '6 Months'), (12, '1 Year'), (24, '2 Years')])),
                ('floor_number', models.PositiveIntegerField()),
                ('unit_number', models.PositiveIntegerField()),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refundable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_date', models.DateField()),
                ('additional_charges', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parking_slot', models.PositiveIntegerField(blank=True, null=True)),
                ('tenant_insurance', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementOwner',
            fields=[
                ('announcement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('post_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationOwner',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('post_date', models.DateField()),
                ('audience', models.CharField(choices=[('Management', 'Management'), ('Tenant', 'Tenant')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Owner.message')),
            ],
        ),
    ]
