# Generated by Django 5.0.6 on 2024-06-26 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addform2',
            name='name',
        ),
    ]
