# Generated by Django 5.0.6 on 2024-06-30 10:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(choices=[('fire', 'Fire'), ('medical', 'Medical Emergency'), ('security', 'Security Threat')], max_length=20)),
                ('emergency_details', models.TextField()),
                ('notify_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidenttype', models.CharField(choices=[('Theft', 'Theft'), ('Vandalism', 'Vandalism'), ('Suspicious_Activity', 'Suspicious Activity'), ('Parking_Violation', 'Parking Violation'), ('Others', 'Others')], max_length=60)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=155)),
                ('datetimereported', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tenant_name', models.CharField(max_length=64)),
                ('floor_number', models.IntegerField()),
                ('unit_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=64)),
                ('home_address', models.TextField()),
                ('reason_to_visit', models.TextField()),
                ('tower_select', models.CharField(choices=[('Tower 1', 'Tower 1'), ('Tower 2', 'Tower 2'), ('Tower 3', 'Tower 3'), ('others', 'Others')])),
                ('datetime_local', models.DateTimeField()),
            ],
        ),
    ]
