# Generated by Django 5.0.6 on 2024-06-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRegistration',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('tenant_name', models.CharField(max_length=64)),
                ('floor_number', models.IntegerField()),
                ('unit_number', models.IntegerField()),
                ('phone_number', models.CharField(max_length=64)),
                ('home_address', models.TextField()),
                ('reason_to_visit', models.TextField()),
                ('tower_select', models.CharField(choices=[('Tower 1', 'Tower 1'), ('Tower 2', 'Tower 2'), ('Tower 3', 'Tower 3'), ('others', 'Others')])),
                ('datetime_local', models.DateTimeField()),
            ],
        ),
    ]
