# Generated by Django 5.0.6 on 2024-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('home_address', models.TextField()),
                ('reason_to_visit', models.TextField()),
                ('tower_select', models.IntegerField(choices=[(1, 'Tower 1'), (2, 'Tower 2'), (3, 'Tower 3'), (4, 'Others')])),
                ('datetime_local', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Qrcode',
        ),
    ]
