# Generated by Django 5.0.6 on 2024-05-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('user_type', models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner'), ('security', 'Security'), ('management', 'Management')], max_length=20)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
