# Generated by Django 5.0.6 on 2024-06-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('usertype', models.CharField(choices=[('Tenant', 'Tenant'), ('Owner', 'Owner'), ('Security', 'Security'), ('Management', 'Management')], max_length=64)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
